# Generated by Django 5.1.4 on 2026-06-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trackingcoordinate",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinates",
                to="matches.match",
            ),
        ),
        migrations.AddIndex(
            model_name="trackingcoordinate",
            index=models.Index(
                fields=["match", "frame_number"], name="matches_tra_match_i_512a4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackingcoordinate",
            index=models.Index(
                fields=["match", "player_id"], name="matches_tra_match_i_cc2e9f_idx"
            ),
        ),
    ]
