# Generated by Django 5.1.4 on 2026-06-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("possession", "Possession Change"),
                            ("pass", "Pass"),
                            ("interception", "Interception"),
                            ("shot", "Shot"),
                            ("sprint", "Sprint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frame_number", models.IntegerField()),
                ("player_initiator", models.IntegerField(blank=True, null=True)),
                ("player_receiver", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(blank=True, max_length=20, null=True)),
                ("x_coord", models.FloatField(blank=True, null=True)),
                ("y_coord", models.FloatField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["match", "event_type"],
                        name="matches_mat_match_i_518d22_idx",
                    ),
                    models.Index(
                        fields=["match", "frame_number"],
                        name="matches_mat_match_i_e4b58d_idx",
                    ),
                ],
            },
        ),
    ]
