# Generated by Django 5.1.4 on 2026-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_matchevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="video_fps",
            field=models.FloatField(default=25.0),
        ),
    ]
